---
apiVersion: app/v1
kind: ReplicationSet
metadata:
  name: mavenwebapprc
  namespace: devopsaws-ns
spec:
  replicas: 3
  selector:
    matchLabels:
     app: mavenwebapp
  template:
    metadata:
      name: mavenwebapprcpod
      labels:
        app: mavenwebapp
    spec:
      containers:
        - name: mavenwebapprccontainer
          image: devopswthaws58/maven-web-app
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: devopsaws-ns
  name: mavenwebapprcsvc
spec:
  type: LoadBalancer
  selector:
    app: mavenwebapp
  ports:
    - port: 80
      targetPort: 8080
...